### ISSUE TITLE
Add iCal export of Indico events

### ISSUE THREAD

**Issue by tgbaron** [indico/indico-drupal-feeds#10]
Dear Thomas,

Is it possible to provide us through the Drupal module the iCal export field of an Indico event?

For now the module provides us with the following fields:
Title, Type, Description, Date, Timezone, Location, Room, Category, Indico link and Room map URL.

Many users have requested to provide them with a link so they can import the events directly to their calendar (like the one you have on Indico - iCal). For now they have to visit the event’s Indico page and then click on iCal, which is two clicks away.

By exporting the iCal field in Drupal will take this down to one click.

Please let me know what you think.

Kind Regards,
Sotirios

**Comment by rwmanos** [comment]
I believe this issue has been resolved by PR #11 but @gasparuben seems to have forgotten to close it. Isn't that right?

**Comment by tgbaron** [comment]
indeed!
